from __future__ import annotations
import json
from pathlib import Path
from typing import Any

def write_json(out_path: Path, payload: dict[str, Any]) -> None:
    out_path.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")

def write_html(out_path: Path, payload: dict[str, Any]) -> None:
    def esc(s: str) -> str:
        return (s.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;")
                 .replace('"',"&quot;").replace("'","&#39;"))

    title = "Hash Audit Benchmark Report"
    rows = ""
    for k, v in payload.items():
        if isinstance(v, (dict, list)):
            rows += f"<tr><th>{esc(str(k))}</th><td><pre>{esc(json.dumps(v, indent=2))}</pre></td></tr>"
        else:
            rows += f"<tr><th>{esc(str(k))}</th><td>{esc(str(v))}</td></tr>"

    html = f"""<!doctype html>
<html>
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>{esc(title)}</title>
  <style>
    body {{ font-family: system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif; margin: 24px; }}
    h1 {{ margin-bottom: 8px; }}
    .sub {{ color: #555; margin-top: 0; }}
    table {{ border-collapse: collapse; width: 100%; }}
    th, td {{ border: 1px solid #ddd; padding: 10px; vertical-align: top; }}
    th {{ width: 220px; text-align: left; background: #f7f7f7; }}
    pre {{ margin: 0; white-space: pre-wrap; word-wrap: break-word; }}
    .footer {{ margin-top: 18px; color: #777; font-size: 12px; }}
  </style>
</head>
<body>
  <h1>{esc(title)}</h1>
  <p class="sub">Generated by <code>hash-audit</code></p>
  <table>
    {rows}
  </table>
  <p class="footer">For education and defensive security auditing only.</p>
</body>
</html>"""
    out_path.write_text(html, encoding="utf-8")
